version: '3.7'

services:
  rabbit-mq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: main
      RABBITMQ_DEFAULT_HOST: localhost
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 30s
      retries: 3